title: CNC Fräse selberbauen
nav:
- Teile vorbereiten.md
- Bau des Untergestells.md
- Montage des Frästischs.md
- Montage des Portals.md
- Montage der Z-Achse.md
- Ausrichten der CNC Fräse.md
- Linearführungen ausrichten.md
- Montage von Kugelumlaufspindeln und Lagern.md
- Montage der Schrittmotoren.md
- Bau des Schaltschranks.md
- Verkabelung der Fräse.md
- Homing in Masso.md
- Learnings beim Zusammenbau.md
- Verbesserungen.md
- parts-lists
